---
title: "Landscape Metrics"
author: "Evan Muise"
date: "9/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rgdal)
library(raster)
library(landscapemetrics)
library(tidyverse)
```

```{r}
class <- c(0, 20, 31, 32, 33, 40, 50, 80, 81, 100, 210, 220, 230)
class_name <- c("unclassifed", "water", "snow/ice", "rock/rubble", "exposed/barren land", "bryoid", "shrubland", "wetland", "wetland-treed", "herbs", "coniferous", "broadleaf", "mixed wood")

lcc_df <- tibble(class, class_name)

dist_class <- c(1000, 1001, 1002, 1003, 1004, 1005)
dist_name <- c("Untyped Disturbance", "Fire", "Harvesting", "Non Stand-Replacing", "Road", "Ag")

dist_df <- tibble(class = dist_class, class_name = dist_name)

raster_class <- rbind(lcc_df, dist_df)
metricFactors <- list("elev_mean" = 1000,
                      "elev_stddev" = 1000,
                      "elev_cv" = 1000,
                      "elev_p95" = 1000,
                      "percentage_first_returns_above_2m" = 100,
                      "percentage_first_returns_above_mean" = 100,
                      "loreys_height" = 1000,
                      "basal_area" = 100,
                      "gross_stem_volume" = 10,
                      "total_biomass" = 100)
struct_names <- list("basal_area" = "Basal Area (m^2ha)", "elev_cv" = "Structure (Elevation Covariance)",
                     "gross_stem_volume" = "Volume (m^3ha^-1)", "loreys_height" = "Height (m)",
                     "percentage_first_returns_above_2m" = "Cover (%)", "total_biomass" = "Biomass (t/ha)")

rm(class, class_name, lcc_df, dist_class, dist_name, dist_df)
```

```{r}
#input a park folder with some tifs in it

hmmAreaFun <- function(park){
  fileNames <- list.files(park, recursive = T, full.names = T)

  fragTifs <- do.call("c", map(fileNames, ~discard(.x, !grepl("HMM.tif$|disturbance.tif$", .x))))
  
  createAreaMetrics <- function(loc){
    inRaster <- raster(loc)
    areaMetric <- lsm_c_ca(inRaster)
    
    year = as.numeric(str_extract_all(loc, "\\d{4}", simplify = T))
    parkName = str_split(loc, pattern = "/")[[1]][3]
    ppa_gpe <- str_split(loc, pattern = "/")[[1]][4]
    varName = str_split(str_split(loc, pattern = "-")[[1]][[3]], "[.]")[[1]][1]
    
    areaMetric <- areaMetric %>% mutate(park = parkName, var = varName, 
                                        ppa_gpe = ifelse(grepl("_GPE$", ppa_gpe), "GPE", "PPA"),
                                        year = year)
  
    return(areaMetric)}
    
  outDf <- map(fragTifs, createAreaMetrics)
  outDf <- do.call("rbind", outDf)
  outDf <- left_join(outDf, raster_class)
  #outDf <- left_join(outDf, dist_df)
  print("done folder")
  return(outDf)
}
```

```{r}
structDistrFun <- function(park){
  fileNames <- list.files(park, recursive = T, full.names = T)
  structTifs <- do.call("c", map(fileNames, ~discard(.x, !grepl("tif$", .x))))
  structTifs <- do.call("c", map(structTifs, ~discard(.x, grepl("HMM.tif$|disturbance.tif$", .x))))
  #loc <- structTifs[2]
  
  createStructDistr <- function(loc){
    
    year = as.numeric(str_extract_all(loc, "\\d{4}", simplify = T))
    parkName = str_split(loc, pattern = "/")[[1]][3]
    ppa_gpe <- str_split(loc, pattern = "/")[[1]][4]
    varName = str_split(str_split(loc, pattern = "-")[[1]][[3]], "[.]")[[1]][1]
    
    
    inRaster <- raster(loc)
    df <- inRaster %>% as.data.frame(xy = TRUE) %>% na.omit() %>% 
    mutate(park = parkName, var = varName, 
           ppa_gpe = ifelse(grepl("_GPE$", ppa_gpe), "GPE", "PPA"),
           year = year)
    colnames(df)[3] <- "value"
    df <- df %>% mutate(value = value / metricFactors[varName][[1]], var2 = struct_names[varName][[1]])
    return(df)
  }
  outDf <- map(structTifs, createStructDistr)
  outDf <- do.call("rbind", outDf)
  print("done folder")
  
  write_csv(outDf, file.path(park, "structDf.csv"))
  return()
}
```


```{r}
parks = list.dirs(path = "./outputs", recursive = F)

hmmDf <- do.call("rbind", map(parks, hmmAreaFun))
hmmDf$ppa_gpe <- as.factor(hmmDf$ppa_gpe) %>% fct_rev()
hmmDf <- hmmDf %>% filter(class != 20)
write_csv(hmmDf, "hmmDf.csv")
map(parks, structDistrFun)
#structDf <- structDistrFun(parks)
#write_csv(structDf, "structDf.csv")
```

```{r}
mann <- hmmDf %>% filter(var =="HMM") %>% filter(park == "Mann") %>% group_by(ppa_gpe) %>%
  mutate(percent_lcc = value / sum(value) * 100)

mann %>% ggplot(aes(x = ppa_gpe, y = percent_lcc, fill = class_name)) +
  geom_bar(stat = "identity") + labs(x = "", y = "Percent Land Cover") +
  theme_bw() + theme(legend.title = element_blank())

ggsave("manning_lcc.png", device = "png", width = 10)
```


```{r}
hmm <- hmmDf %>% filter(var == "HMM")  %>% group_by(park, ppa_gpe) %>%
  mutate(percent_lcc = value / sum(value) * 100)

hmm %>% ggplot(aes(x = class_name, y = percent_lcc, fill = class_name)) +
  geom_col() + facet_grid(rows = vars(ppa_gpe), cols = vars(park)) + 
  labs(y = "Percent land cover", 
       title = "2015 Land Cover Classes as Percent of Total Area",
       subtitle = "for PPA and GPE") + 
  theme_bw() + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(size = 10))

ggsave("2015_lcc_percents_pSubsets.png", device = "png")
```

```{r}
hmm %>% ggplot(aes(x = ppa_gpe, y = percent_lcc, fill = class_name)) +
  geom_bar(stat = "identity") + facet_wrap(. ~ park) + theme_bw() +
  theme(legend.title = element_blank()) + labs(x = "", y = "Percent of total land cover")
```


```{r}
dist <- hmmDf %>% filter(var == "disturbance", class != 0) %>% group_by(park, ppa_gpe) %>%
  mutate(percent_dist = value / manning_area * 100)
unique(dist$class_name)

dist %>% ggplot(aes(x = ppa_gpe, y = percent_dist, fill = class_name)) +
  geom_bar(stat = "identity") + facet_wrap(. ~ park) +theme_bw() + 
  labs(x = "", y = "Percent of total disturbance") +
  theme(legend.title = element_blank())

ggsave("2015_dist_percents_pSubsets.png", device = "png")
```

```{r}
ekwanStruct <- structDf %>% filter(park == "EkwanLakeProtectedArea")
ekwanStruct$ppa_gpe <- as.factor(ekwanStruct$ppa_gpe) %>% fct_rev()

structDf$ppa_gpe <- as.factor(structDf$ppa_gpe) %>% fct_rev()
structDf <- structDf %>% filter(!(var == "elev_cv" & value > 1))

structDf %>% ggplot(aes(x = value, colour = ppa_gpe)) +
  geom_freqpoly() + 
  facet_wrap(var2 ~ ., scale = "free",
              labeller = labeller(var2 = label_wrap_gen(25))) + 
  theme_bw() +
  theme(legend.title = element_blank()) +
  labs(x = "Pixel Value", y = "Number of Pixels")

ggsave("2015_Mann_Struct.png", device = "png", width = 10)
```

```{r}
mannDist2015 <- read_csv("2015_mann_disturbance.csv") %>% filter(disturbance != "Agriculture")
mannDist2015$ppa_gpe <- fct_rev(mannDist2015$ppa_gpe) 

mannDist2015 %>% ggplot(aes(x = disturbance, y= per_disturbance, fill = ppa_gpe)) +
  geom_bar(position = "dodge", stat = "identity") + theme_bw() +
  theme(legend.title = element_blank()) +
  labs(y = "Percent of PPA Area Disturbed", x = "")
ggsave("2015_mann_dist_all.png", device = "png", width = 10)


mannDist2015 %>% filter(disturbance != "Harvesting") %>%
  ggplot(aes(x = disturbance, y= per_disturbance, fill = ppa_gpe)) +
  geom_bar(position = "dodge", stat = "identity") + theme_bw() +
  theme(legend.title = element_blank()) +
  labs(y = "Percent of PPA Area Disturbed", x = "")
ggsave("2015_mann_dist_nh.png", device = "png", width = 10)
```

```{r}
mannHMM <- hmmDf %>% filter(park == "Mann" & var == "HMM" & value > 500) %>% mutate(percent_lcc = value / sum(value) * 100)

mannHMM$class_name <- fct_reorder(mannHMM$class_name, mannHMM$value, sum, .desc = T)

mannHMM %>% ggplot(aes(x = class_name, y= percent_lcc, fill = ppa_gpe)) +
  geom_bar(position = "dodge", stat = "identity") + theme_bw() +
  theme(legend.title = element_blank()) +
  labs(y = "Percent of PPA Area", x = "") +
  scale_x_discrete(guide = guide_axis(n.dodge = 2))

ggsave("2015_mann_lcc.png", device = "png", width = 10)
```


